<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="2" tests="2" name="Default test" time="2.345" errors="0" timestamp="2025-01-02T20:04:04 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.522">
    <failure type="java.lang.AssertionError" message="Unexpected status code expected [201] but found [208]">
      <![CDATA[java.lang.AssertionError: Unexpected status code expected [201] but found [208]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at stepDefinitions.BookApiSteps.iShouldReceiveAResponseWithStatusCode(BookApiSteps.java:46)
at ✽.I should receive a response with status code 201(file:///C:/Users/shakthi/eclipse-workspace/BDDFramework_BackEnd/src/test/resources/features/createBook.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.195">
    <failure type="java.lang.AssertionError" message="Unexpected status code expected [400] but found [201]">
      <![CDATA[java.lang.AssertionError: Unexpected status code expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at stepDefinitions.BookApiSteps.iShouldReceiveAResponseWithStatusCode(BookApiSteps.java:46)
at ✽.I should receive a response with status code 400(file:///C:/Users/shakthi/eclipse-workspace/BDDFramework_BackEnd/src/test/resources/features/createBook.feature:17)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
